****Y2K****

DO BASCOM
DO BASSTO
DO BASVEN

PUBLIC BSTO,ICSTO,INSTO,IPSTO,ITSTO,IASTO && PRODUCTOS 
  BSTO = "STO" +abrclim
  ICSTO= "CSTO"+abrclim
  INSTO= "NSTO"+abrclim
  IPSTO= "LSTO"+abrclim
  ITSTO= "TSTO"+abrclim
  IASTO= "ASTO"+abrclim
PUBLIC BTIP,ICTIP,INTIP             && TIPOS DE PRODUCTOS
  BTIP = "TIP" +abrclim
  ICTIP= "CTIP"+abrclim
  INTIP= "NTIP"+abrclim
PUBLIC BCED,ICCED,INCED             && PROCEDENCIA DE PRODUCTOS
  BCED = "CED" +abrclim
  ICCED= "CCED"+abrclim
  INCED= "NCED"+abrclim
PUBLIC BTAR,ICTAR,INTAR             && TARJETAS DE CREDITO
  BTAR = "TAR" +abrclim
  ICTAR= "CTAR"+abrclim
  INTAR= "NTAR"+abrclim
