** APERTURA DE ARCHIVOS
SELE 57
USE cierreca
INDEX ON codcierre TO CIECA01 UNIQUE

SELE 58
USE cierreDE
INDEX ON STR(codcierre)+STR(COD) TO CIEDE01 UNIQUE
INDEX ON STR(codcierre)+NOM TO CIEDE02 
INDEX ON art+str(cod,6)+STR(codcierre,6) TO CIEDE03 
